### ISSUE TITLE
Add support for AD2S1210

### ISSUE THREAD

**Issue by pamolloy** [analogdevicesinc/PrecisionToolbox#6]
## Tasks

- [x] If not already setup, setup hardware for testing
- [x] Install pre-built Toolbox installer on Windows machine in hardware setup
- [x] Build Toolbox installer locally and update documentation as necessary

## Dependencies

- adi-ses/sea-misc/issues/7
- adi-ses/sea-misc/issues/2
- analogdevicesinc/hdl/issues/1147 (optional)
- adi-ses/sea-misc/issues/16

**Comment by apelete** [comment]
Progress report :

Made some changes by following the example of AD463x implementation (eg. base class implementation + Rx Resolver-to-Digital Converter class) ; base class might not be needed since it is only used by the one Rx class so far.

Facing an issue trying to build the PrecisionToolbox v21.2.1 from sources on Linux for a MATLAB 2023a release.
According to [How do I install additional toolboxes into an existing installation of MATLAB](https://www.mathworks.com/matlabcentral/answers/101885-how-do-i-install-additional-toolboxes-into-an-existing-installation-of-matlab) :
`Toolboxes must match the release of MATLAB they are installed into, e.g. you cannot install a toolbox for MATLAB R2022b into MATLAB R2023a`

Are there specific instructions to build and install Precision Toolbox on Linux for a MATLAB 2023a release ?

**Comment by pamolloy** [comment]
Based on a conversation with @mike-bradley, looks like we should use `make -C ./CI/scripts gen_tlbx`.

The Vivado dependency is used for new projects that will use Matlab to define logic in the FPGA.

**Comment by apelete** [comment]
Opened [Pull-Request #11](https://github.com/analogdevicesinc/PrecisionToolbox/pull/11) to submit AD2S1210 initial support proposal.

**Comment by apelete** [comment]
> Based on a conversation with @mike-bradley, looks like we should use `make -C ./CI/scripts gen_tlbx` (see [Jenkinsfile#L27](https://github.com/analogdevicesinc/PrecisionToolbox/blob/main/Jenkinsfile#L27)).

That command to build the toolbox fails when trying to build for R2023a because the scripts are hard-coded to build for R2021b only : I have a patch that fixes this issue and I can submit it if deemed useful.

**Comment by mike-bradley** [comment]
From talking with the team who supports the internal building of the matlab toolboxes, they're all on R2012b on the internal CI setup. 
Not sure what the reasons are for that version or if there are reasons why they don't/can't switch, but we'd need to direct that questions to the right people in COS internally.

**Comment by pamolloy** [comment]
We just happened to install the latest version before realizing that they're using 2021. We've added a note to track it, but there shouldn't be anything we need to do about it now
