### ISSUE TITLE
Add support for AD4000

### ISSUE THREAD

**Issue by pamolloy** [analogdevicesinc/PrecisionToolbox#9]
## Hardware

- [ ] MX1002 → EVAL-AD4000FMCZ → ZedBoard
- [ ] MX1002 → EVAL-AD4001FMCZ → ZedBoard
- [ ] MX1002 → EVAL-AD4002FMCZ → ZedBoard
- [ ] MX1002 → EVAL-AD4003FMCZ → ZedBoard
- [ ] MX1002 → EVAL-AD4020FMCZ → ZedBoard
- [ ] MX1002 → EVAL-ADAQ4001PMDZ → EVAL-PMD-IB1Z → ZedBoard
- [ ] MX1002 → EVAL-ADAQ4003PMDZ → EVAL-PMD-IB1Z → ZedBoard

## Tasks

- [ ] If not already setup, setup hardware for testing

## Dependencies

- analogdevicesinc/hdl/issues/1152
- analogdevicesinc/precision-converters-firmware/issues/4
